// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * ArtStyleResponse
 *
 * ``GET /art-styles`` 응답 항목. ``samples``는 카드 유형별 견본 URL(화풍 선택 화면용).
 */
export type ArtStyleResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Label
     */
    label: string;
    /**
     * Samples
     */
    samples: {
        [key: string]: string;
    };
};

/**
 * ArtStyleUpdateRequest
 *
 * ``PUT /works/{work_id}/art-style`` 요청 바디. ``art_style_note``는 빈 문자열도 허용한다.
 */
export type ArtStyleUpdateRequest = {
    /**
     * Artstyleid
     */
    artStyleId: string;
    /**
     * Artstylenote
     */
    artStyleNote?: string | null;
};

/**
 * AttributeChange
 *
 * 기존 엔티티의 속성 변경 후보.
 */
export type AttributeChange = {
    /**
     * Entityid
     */
    entityId: string;
    /**
     * Attribute
     */
    attribute: string;
    /**
     * Newvalue
     */
    newValue: string;
};

/**
 * BeatSheetResponse
 *
 * 비트 시트 생성 응답 — 회차별 비트를 한 줄씩 담는다(예: "1화: 발단 — ...").
 */
export type BeatSheetResponse = {
    /**
     * Beats
     */
    beats: Array<string>;
};

/**
 * CandidateEntity
 *
 * LLM이 발견한, 아직 카드가 없는 신규 엔티티 후보.
 */
export type CandidateEntity = {
    /**
     * Name
     */
    name: string;
    /**
     * Summary
     */
    summary?: string;
};

/**
 * ChangePasswordRequest
 *
 * Request body for POST /auth/change-password (authenticated).
 */
export type ChangePasswordRequest = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * ChangePasswordResponse
 *
 * Response body for POST /auth/change-password.
 */
export type ChangePasswordResponse = {
    /**
     * Message
     */
    message?: string;
};

/**
 * ChapterCreate
 *
 * 챕터 생성 입력. ``global_seq``는 서버가 부여하므로 입력에 없다.
 */
export type ChapterCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Orderindex
     */
    orderIndex: number;
    /**
     * Body
     */
    body?: string;
};

/**
 * ChapterResponse
 *
 * 챕터 응답 — 본문(``body``)을 직접 보유한다(scenes 계층 폐지, remove-scene ADR).
 */
export type ChapterResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Workid
     */
    workId: string;
    /**
     * Episodeid
     */
    episodeId: string;
    /**
     * Title
     */
    title: string;
    /**
     * Orderindex
     */
    orderIndex: number;
    /**
     * Globalseq
     */
    globalSeq: number;
    /**
     * Body
     */
    body: string;
    /**
     * Summary
     */
    summary?: string | null;
};

/**
 * ChapterUpdate
 *
 * 챕터 수정 입력 — 모든 필드 선택(PATCH). ``global_seq``는 수정 불가.
 */
export type ChapterUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Orderindex
     */
    orderIndex?: number | null;
    /**
     * Body
     */
    body?: string | null;
    /**
     * Summary
     */
    summary?: string | null;
};

/**
 * ChapterVersionDetailResponse
 *
 * 버전 단건 응답 — 본문·요약 포함.
 */
export type ChapterVersionDetailResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Body
     */
    body: string;
    /**
     * Summary
     */
    summary?: string | null;
};

/**
 * ChapterVersionListItem
 *
 * 버전 목록 한 항목 — 본문은 싣지 않는다(plan.md #72 S3, 목록 경량화).
 */
export type ChapterVersionListItem = {
    /**
     * Id
     */
    id: string;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Charcount
     */
    charCount: number;
    /**
     * Chardelta
     */
    charDelta: number | null;
    /**
     * Hassummary
     */
    hasSummary: boolean;
};

/**
 * ChapterVersionListResponse
 *
 * 버전 목록 응답 — 최신순, 전체 개수 포함(저장소 최초의 페이지네이션, ADR).
 */
export type ChapterVersionListResponse = {
    /**
     * Items
     */
    items: Array<ChapterVersionListItem>;
    /**
     * Total
     */
    total: number;
};

/**
 * ChatMessage
 *
 * A single message in a conversation turn.
 *
 * Attributes
 * ----------
 * role:
 * Speaker role — ``"user"``, ``"assistant"``, or ``"system"``.
 * Unknown roles default to ``HumanMessage``.
 * content:
 * Text content of the message.
 */
export type ChatMessage = {
    /**
     * Role
     */
    role: string;
    /**
     * Content
     */
    content: string;
};

/**
 * ChatRequest
 *
 * Request body for chat endpoints.
 *
 * Attributes
 * ----------
 * messages:
 * Ordered conversation history.  Must contain at least one message.
 * system:
 * Optional system prompt prepended before all other messages.
 * Equivalent to adding a ``{"role": "system", ...}`` entry at the front.
 */
export type ChatRequest = {
    /**
     * Messages
     */
    messages: Array<ChatMessage>;
    /**
     * System
     */
    system?: string | null;
};

/**
 * ChatResponse
 *
 * Response body for the non-streaming ``/complete`` endpoint.
 *
 * Attributes
 * ----------
 * content:
 * The model's full reply text.
 * model:
 * Active LiteLLM model identifier, e.g. ``"openai/gpt-4o-mini"``.
 * Included for debugging and provider-routing verification.
 */
export type ChatResponse = {
    /**
     * Content
     */
    content: string;
    /**
     * Model
     */
    model?: string | null;
};

/**
 * ConflictResponse
 *
 * 설정 충돌 1건 — 같은 엔티티·같은 예약 state_key에 대한 시점 역행 모순 쌍.
 */
export type ConflictResponse = {
    /**
     * Entityid
     */
    entityId: string;
    /**
     * Entityname
     */
    entityName: string;
    /**
     * Statekey
     */
    stateKey: string;
    earlier: ConflictStateRef;
    later: ConflictStateRef;
};

/**
 * ConflictStateRef
 *
 * 충돌 쌍의 한쪽 타임라인 상태.
 */
export type ConflictStateRef = {
    /**
     * Id
     */
    id: string;
    /**
     * Chapterid
     */
    chapterId: string;
    /**
     * Globalseq
     */
    globalSeq: number;
    /**
     * Statevalue
     */
    stateValue: string;
    /**
     * Createdat
     */
    createdAt: string;
};

/**
 * ContinueRequest
 */
export type ContinueRequest = {
    /**
     * Cursortext
     */
    cursorText: string;
};

/**
 * ConversationCreate
 *
 * Request body for POST /chat/conversations.
 */
export type ConversationCreate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * System Prompt
     */
    system_prompt?: string | null;
    /**
     * Work Id
     */
    work_id?: string | null;
};

/**
 * ConversationResponse
 */
export type ConversationResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Work Id
     */
    work_id: string | null;
    /**
     * Title
     */
    title: string | null;
    /**
     * System Prompt
     */
    system_prompt: string | null;
    /**
     * Model Name
     */
    model_name: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * CorrectRequest
 */
export type CorrectRequest = {
    /**
     * Text
     */
    text: string;
};

/**
 * DialogueRequest
 */
export type DialogueRequest = {
    /**
     * Intent
     */
    intent: string;
    /**
     * Targetentityid
     */
    targetEntityId: string;
};

/**
 * DraftRequest
 *
 * 늘려쓰기 입력 — 화 요약(작가가 모달에서 손본 것일 수 있어 바디로 받는다).
 */
export type DraftRequest = {
    /**
     * Text
     */
    text: string;
};

/**
 * EmbeddingSourceType
 *
 * 임베딩 출처 판별 타입 (data-model.md 6장).
 */
export type EmbeddingSourceType = 'entity' | 'chapter';

/**
 * EntityCreate
 *
 * 엔티티 카드 생성 입력. ``attributes``는 서비스 레벨에서 ``entity_type``별로 검증한다.
 */
export type EntityCreate = {
    entityType: EntityType;
    /**
     * Name
     */
    name: string;
    /**
     * Aliases
     */
    aliases?: Array<string>;
    /**
     * Summary
     */
    summary?: string;
    /**
     * Attributes
     */
    attributes?: {
        [key: string]: unknown;
    };
};

/**
 * EntityImageResponse
 *
 * 설정 이미지 한 항목. ``image_url``은 바이트 조회 엔드포인트의 경로를 담는다 —
 * ``ArtStyleResponse.samples``가 쓰는 것과 같은 방식이다.
 */
export type EntityImageResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Imageurl
     */
    imageUrl: string;
    /**
     * Isprimary
     */
    isPrimary: boolean;
    /**
     * Visualdescription
     */
    visualDescription: string | null;
    /**
     * Templateid
     */
    templateId: string;
    /**
     * Createdat
     */
    createdAt: string;
};

/**
 * EntityResponse
 *
 * 엔티티 카드 응답.
 */
export type EntityResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Workid
     */
    workId: string;
    entityType: EntityType;
    /**
     * Name
     */
    name: string;
    /**
     * Aliases
     */
    aliases: Array<string>;
    /**
     * Summary
     */
    summary: string;
    /**
     * Attributes
     */
    attributes: {
        [key: string]: unknown;
    };
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Updatedat
     */
    updatedAt: string;
};

/**
 * EntityType
 *
 * 엔티티 카드 판별 타입 (data-model.md 3.1).
 */
export type EntityType = 'character' | 'location' | 'event' | 'item';

/**
 * EntityUpdate
 *
 * 엔티티 카드 수정 입력 — 모든 필드 선택(PATCH).
 *
 * ``entity_type``은 생성 후 불변이라 필드 자체가 없다 — 웹 mock ``updateEntity``의
 * "type(카테고리)은 변경 불가" 규칙과 동일하게, 페이로드에 담겨도 무시된다.
 */
export type EntityUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Aliases
     */
    aliases?: Array<string> | null;
    /**
     * Summary
     */
    summary?: string | null;
    /**
     * Attributes
     */
    attributes?: {
        [key: string]: unknown;
    } | null;
};

/**
 * EpisodeCreate
 *
 * 부 생성 입력.
 */
export type EpisodeCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Orderindex
     */
    orderIndex: number;
};

/**
 * EpisodeResponse
 *
 * 부 응답.
 */
export type EpisodeResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Workid
     */
    workId: string;
    /**
     * Title
     */
    title: string;
    /**
     * Orderindex
     */
    orderIndex: number;
};

/**
 * EpisodeUpdate
 *
 * 부 수정 입력 — 모든 필드 선택(PATCH).
 */
export type EpisodeUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Orderindex
     */
    orderIndex?: number | null;
};

/**
 * ExtractUpdatesResponse
 *
 * 추출 결과 — 3개 카테고리. 파싱 실패 시 모두 빈 리스트.
 */
export type ExtractUpdatesResponse = {
    /**
     * Candidateentities
     */
    candidateEntities?: Array<CandidateEntity>;
    /**
     * Attributechanges
     */
    attributeChanges?: Array<AttributeChange>;
    /**
     * Timelinechanges
     */
    timelineChanges?: Array<TimelineChange>;
};

/**
 * GenerateEntityImageRequest
 *
 * ``templateId``를 받지 않는다 — 작품의 화풍을 읽어 조립한다(S5, ADR `260813-110724`).
 *
 * 옛 웹이 여전히 ``templateId``를 보내더라도(2/2 배포 전까지) ``_CamelModel``의 기본
 * ``extra="ignore"``가 조용히 걸러낸다 — 거부하면 2/2가 들어오기 전까지 로그가
 * 시끄러워지므로 무시를 택했다(plan.md S5 확인 필요 항목).
 */
export type GenerateEntityImageRequest = {
    /**
     * Extraprompt
     */
    extraPrompt?: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InfillRequest
 */
export type InfillRequest = {
    /**
     * Beforetext
     */
    beforeText: string;
    /**
     * Aftertext
     */
    afterText: string;
};

/**
 * LoginRequest
 *
 * Request body for POST /auth/login.
 */
export type LoginRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * LogoutRequest
 *
 * Request body for POST /auth/logout.
 */
export type LogoutRequest = {
    /**
     * Refresh Token
     */
    refresh_token: string;
};

/**
 * MemoryItemResponse
 *
 * 메모리 검색 결과 1건. ``priority``: 1=링크 엔티티, 2=타임라인 상태, 3=벡터 매칭.
 */
export type MemoryItemResponse = {
    type: MemoryItemType;
    /**
     * Priority
     */
    priority: number;
    /**
     * Entityid
     */
    entityId?: string | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Summary
     */
    summary?: string | null;
    /**
     * Statekey
     */
    stateKey?: string | null;
    /**
     * Statevalue
     */
    stateValue?: string | null;
    /**
     * Note
     */
    note?: string | null;
    sourceType?: EmbeddingSourceType | null;
    /**
     * Sourceid
     */
    sourceId?: string | null;
    /**
     * Content
     */
    content?: string | null;
};

/**
 * MemoryItemType
 *
 * 병합된 메모리 항목의 종류.
 */
export type MemoryItemType = 'entity' | 'timeline_state' | 'vector_match';

/**
 * MessageResponse
 */
export type MessageResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Conversation Id
     */
    conversation_id: string;
    /**
     * Role
     */
    role: string;
    /**
     * Content
     */
    content: string;
    /**
     * Token Count
     */
    token_count: number | null;
    /**
     * Finish Reason
     */
    finish_reason: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * OAuthLoginURLResponse
 *
 * Response body for GET /auth/oauth/{provider}/login.
 */
export type OAuthLoginUrlResponse = {
    /**
     * Authorization Url
     */
    authorization_url: string;
    /**
     * State
     */
    state: string;
};

/**
 * PasswordResetConfirmRequest
 *
 * Request body for POST /auth/password-reset/confirm.
 */
export type PasswordResetConfirmRequest = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PasswordResetConfirmResponse
 *
 * Response body for POST /auth/password-reset/confirm.
 */
export type PasswordResetConfirmResponse = {
    /**
     * Message
     */
    message?: string;
};

/**
 * PasswordResetRequest
 *
 * Request body for POST /auth/password-reset (request reset link).
 */
export type PasswordResetRequest = {
    /**
     * Email
     */
    email: string;
};

/**
 * PasswordResetRequestResponse
 *
 * Response body for POST /auth/password-reset.
 *
 * The message is intentionally generic to prevent account enumeration.
 */
export type PasswordResetRequestResponse = {
    /**
     * Message
     */
    message?: string;
};

/**
 * ProviderInfoResponse
 *
 * Response body for the ``/provider`` info endpoint.
 *
 * Attributes
 * ----------
 * provider:
 * Active provider name, e.g. ``"openai"``, ``"ollama"``.
 * model:
 * Base model name, e.g. ``"gpt-4o-mini"``, ``"llama3.2"``.
 * litellm_model:
 * Full LiteLLM model identifier, e.g. ``"openai/gpt-4o-mini"``.
 */
export type ProviderInfoResponse = {
    /**
     * Provider
     */
    provider: string;
    /**
     * Model
     */
    model: string;
    /**
     * Litellm Model
     */
    litellm_model: string;
};

/**
 * RefreshRequest
 *
 * Request body for POST /auth/refresh.
 */
export type RefreshRequest = {
    /**
     * Refresh Token
     */
    refresh_token: string;
};

/**
 * RelationshipEdge
 *
 * 관계 그래프의 방향성 있는 엣지 한 건.
 */
export type RelationshipEdge = {
    /**
     * Sourceentityid
     */
    sourceEntityId: string;
    /**
     * Sourcename
     */
    sourceName: string;
    /**
     * Targetentityid
     */
    targetEntityId: string;
    /**
     * Targetname
     */
    targetName: string;
    /**
     * Type
     */
    type: string;
    /**
     * Note
     */
    note: string | null;
};

/**
 * RelationshipGraphResponse
 *
 * 관계 그래프 응답 — ``up_to_chapter_id`` 미지정 시 ``summary``는 null.
 */
export type RelationshipGraphResponse = {
    /**
     * Edges
     */
    edges: Array<RelationshipEdge>;
    /**
     * Summary
     */
    summary?: string | null;
};

/**
 * ReviewSummary
 */
export type ReviewSummary = {
    /**
     * Scenes
     */
    scenes?: number;
    /**
     * States
     */
    states?: number;
    /**
     * Conflicts
     */
    conflicts?: number;
};

/**
 * SceneEntityLinkCreate
 *
 * 씬-엔티티 링크 생성 입력. ``source``는 서비스에서 ``author``로 고정된다.
 */
export type SceneEntityLinkCreate = {
    /**
     * Entityid
     */
    entityId: string;
};

/**
 * SceneEntityLinkResponse
 *
 * 씬-엔티티 링크 응답.
 */
export type SceneEntityLinkResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Workid
     */
    workId: string;
    /**
     * Chapterid
     */
    chapterId: string;
    /**
     * Entityid
     */
    entityId: string;
    source: SceneEntityLinkSource;
    /**
     * Createdat
     */
    createdAt: string;
};

/**
 * SceneEntityLinkSource
 *
 * 씬-엔티티 링크 출처 (data-model.md 5.1). 이 슬라이스는 ``author``만 기록한다.
 */
export type SceneEntityLinkSource = 'author' | 'ai_extracted';

/**
 * SendMessageRequest
 *
 * Request body for POST /chat/conversations/{id}/messages.
 */
export type SendMessageRequest = {
    /**
     * Content
     */
    content: string;
    /**
     * Stream
     *
     * When True, response is SSE-streamed. When False, returns full JSON.
     */
    stream?: boolean;
};

/**
 * SendWorkChatMessageRequest
 */
export type SendWorkChatMessageRequest = {
    /**
     * Content
     */
    content: string;
    /**
     * Chapterid
     */
    chapterId: string;
};

/**
 * SignupRequest
 *
 * Request body for POST /auth/signup.
 */
export type SignupRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Display Name
     */
    display_name: string;
};

/**
 * SignupResponse
 *
 * Response body for POST /auth/signup.
 */
export type SignupResponse = {
    user: UserResponse;
    /**
     * Message
     */
    message?: string;
};

/**
 * StyleRequest
 */
export type StyleRequest = {
    /**
     * Text
     */
    text: string;
    /**
     * Targetstyle
     */
    targetStyle: string;
};

/**
 * SuggestionKind
 *
 * 제안 종류 (plan.md M3-S2).
 */
export type SuggestionKind = 'new_entity' | 'attribute_change' | 'timeline_state';

/**
 * SuggestionStatus
 *
 * 제안 검토 상태.
 */
export type SuggestionStatus = 'pending' | 'approved' | 'rejected';

/**
 * SummaryRequest
 *
 * 화 요약 입력 — 화 본문 전체(DB 미저장 draft를 반영하려 바디로 받는다).
 */
export type SummaryRequest = {
    /**
     * Text
     */
    text: string;
};

/**
 * SynopsisContinueRequest
 *
 * 기획의도 AI 이어쓰기 입력 — 클라이언트가 보낸 현재 초안 텍스트(task #53).
 */
export type SynopsisContinueRequest = {
    /**
     * Text
     */
    text: string;
};

/**
 * SynopsisResponse
 *
 * 시놉시스 응답.
 */
export type SynopsisResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Workid
     */
    workId: string;
    /**
     * Body
     */
    body: string;
};

/**
 * SynopsisUpdate
 *
 * 시놉시스 upsert 입력.
 */
export type SynopsisUpdate = {
    /**
     * Body
     */
    body?: string;
};

/**
 * TimelineChange
 *
 * 기존 엔티티의 타임라인 상태 변화 후보(예: life_status=dead).
 */
export type TimelineChange = {
    /**
     * Entityid
     */
    entityId: string;
    /**
     * Statekey
     */
    stateKey: string;
    /**
     * Statevalue
     */
    stateValue: string;
};

/**
 * TimelineStateCreate
 *
 * 타임라인 상태 생성 입력. ``source``는 서비스에서 ``author``로 고정된다.
 */
export type TimelineStateCreate = {
    /**
     * Chapterid
     */
    chapterId: string;
    /**
     * Statekey
     */
    stateKey: string;
    /**
     * Statevalue
     */
    stateValue: string;
    /**
     * Note
     */
    note?: string | null;
};

/**
 * TimelineStateResponse
 *
 * 타임라인 상태 응답.
 */
export type TimelineStateResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Workid
     */
    workId: string;
    /**
     * Entityid
     */
    entityId: string;
    /**
     * Chapterid
     */
    chapterId: string;
    /**
     * Statekey
     */
    stateKey: string;
    /**
     * Statevalue
     */
    stateValue: string;
    /**
     * Note
     */
    note: string | null;
    source: TimelineStateSource;
    /**
     * Createdat
     */
    createdAt: string;
};

/**
 * TimelineStateSource
 *
 * 타임라인 상태 출처 (data-model.md 4.1). 이 슬라이스는 ``author``만 기록한다.
 */
export type TimelineStateSource = 'author' | 'ai_suggested';

/**
 * TitleRequest
 */
export type TitleRequest = {
    /**
     * Text
     */
    text: string;
};

/**
 * TokenResponse
 *
 * JWT pair returned by login and refresh endpoints.
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Refresh Token
     */
    refresh_token: string;
    /**
     * Token Type
     */
    token_type?: 'bearer';
    /**
     * Expires In
     *
     * Access token TTL in seconds.
     */
    expires_in: number;
};

/**
 * UpdateEntityImageRequest
 *
 * 부분 갱신 — 보낸 필드만 반영한다(``exclude_unset``, worldbible·manuscript와 동일 방식).
 *
 * ``is_primary``는 ``True``만 받는다: 대표는 **다른 장을 올리는 것으로만** 바뀐다. 내리기만
 * 허용하면 "이미지가 있는데 대표가 없는 카드"가 생겨 카드가 얼굴을 잃는다 — 이미지가
 * 1장 이상인 카드는 대표가 정확히 1장이라는 불변식을 여기서 지킨다.
 */
export type UpdateEntityImageRequest = {
    /**
     * Isprimary
     */
    isPrimary?: true | null;
    /**
     * Visualdescription
     */
    visualDescription?: string | null;
};

/**
 * UpdateProfileRequest
 *
 * Request body for PATCH /auth/me (partial profile update).
 */
export type UpdateProfileRequest = {
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Avatar Emoji
     */
    avatar_emoji?: string | null;
    /**
     * Theme
     */
    theme?: 'light' | 'dark' | 'system' | null;
};

/**
 * UpdateSuggestionResponse
 *
 * 업데이트 제안 응답 (plan.md M3-S2). ``payload`` 모양은 ``kind``에 따라 다르다.
 */
export type UpdateSuggestionResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Workid
     */
    workId: string;
    /**
     * Chapterid
     */
    chapterId: string;
    kind: SuggestionKind;
    /**
     * Payload
     */
    payload: {
        [key: string]: unknown;
    };
    status: SuggestionStatus;
    /**
     * Createdat
     */
    createdAt: string;
};

/**
 * UserResponse
 *
 * Public user representation — never includes hashed_password.
 */
export type UserResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name: string | null;
    /**
     * Avatar Emoji
     */
    avatar_emoji: string | null;
    /**
     * Theme
     */
    theme: 'light' | 'dark' | 'system';
    /**
     * Is Verified
     */
    is_verified: boolean;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VerifyEmailResponse
 *
 * Response body for POST /auth/verify-email/{token}.
 */
export type VerifyEmailResponse = {
    /**
     * Message
     */
    message?: string;
    user: UserResponse;
};

/**
 * WorkArtStyleResponse
 *
 * ``GET``/``PUT /works/{work_id}/art-style`` 응답. 화풍 미지정 작품은 두 필드 모두 ``null``.
 */
export type WorkArtStyleResponse = {
    /**
     * Artstyleid
     */
    artStyleId: string | null;
    /**
     * Artstylenote
     */
    artStyleNote: string | null;
};

/**
 * WorkCreate
 *
 * 작품 생성 입력 — 프론트 ``NewWorkInput``.
 */
export type WorkCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Genre
     */
    genre: string;
    /**
     * Keywords
     */
    keywords?: Array<string>;
    /**
     * Style
     */
    style: string;
};

/**
 * WorkResponse
 *
 * 작품 응답 — 프론트 ``Work``의 비중첩 필드 + 파생(stats·reviewSummary·lastEditedLabel).
 *
 * 중첩 컬렉션(chapters·entities·timeline·conflicts)은 각 도메인 엔드포인트 소관이라 제외한다.
 */
export type WorkResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Shortlabel
     */
    shortLabel: string;
    /**
     * Genre
     */
    genre: string;
    /**
     * Subgenre
     */
    subGenre: string;
    /**
     * Keywords
     */
    keywords: Array<string>;
    /**
     * Style
     */
    style: string;
    /**
     * Status
     */
    status: string;
    /**
     * Covertheme
     */
    coverTheme: string;
    /**
     * Lasteditedlabel
     */
    lastEditedLabel: string;
    stats: WorkStats;
    reviewSummary: ReviewSummary;
};

/**
 * WorkStats
 */
export type WorkStats = {
    /**
     * Chapters
     */
    chapters?: number;
    /**
     * Words
     */
    words?: string;
    /**
     * Wordsunit
     */
    wordsUnit?: string;
    /**
     * Characters
     */
    characters?: number;
    /**
     * Progress
     */
    progress?: number;
};

/**
 * WorkUpdate
 *
 * 작품 수정 입력 — 모든 필드 선택(PATCH).
 */
export type WorkUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Shortlabel
     */
    shortLabel?: string | null;
    /**
     * Genre
     */
    genre?: string | null;
    /**
     * Subgenre
     */
    subGenre?: string | null;
    /**
     * Keywords
     */
    keywords?: Array<string> | null;
    /**
     * Style
     */
    style?: string | null;
    /**
     * Status
     */
    status?: string | null;
    /**
     * Covertheme
     */
    coverTheme?: string | null;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Response Health Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetReadyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ready';
};

export type GetReadyResponses = {
    /**
     * Response Ready Ready Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type GetReadyResponse = GetReadyResponses[keyof GetReadyResponses];

export type PostApiV1AuthSignupData = {
    body: SignupRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/signup';
};

export type PostApiV1AuthSignupErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1AuthSignupError = PostApiV1AuthSignupErrors[keyof PostApiV1AuthSignupErrors];

export type PostApiV1AuthSignupResponses = {
    /**
     * Successful Response
     */
    201: SignupResponse;
};

export type PostApiV1AuthSignupResponse = PostApiV1AuthSignupResponses[keyof PostApiV1AuthSignupResponses];

export type PostApiV1AuthVerifyEmailByTokenData = {
    body?: never;
    path: {
        /**
         * Token
         */
        token: string;
    };
    query?: never;
    url: '/api/v1/auth/verify-email/{token}';
};

export type PostApiV1AuthVerifyEmailByTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1AuthVerifyEmailByTokenError = PostApiV1AuthVerifyEmailByTokenErrors[keyof PostApiV1AuthVerifyEmailByTokenErrors];

export type PostApiV1AuthVerifyEmailByTokenResponses = {
    /**
     * Successful Response
     */
    200: VerifyEmailResponse;
};

export type PostApiV1AuthVerifyEmailByTokenResponse = PostApiV1AuthVerifyEmailByTokenResponses[keyof PostApiV1AuthVerifyEmailByTokenResponses];

export type PostApiV1AuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type PostApiV1AuthLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1AuthLoginError = PostApiV1AuthLoginErrors[keyof PostApiV1AuthLoginErrors];

export type PostApiV1AuthLoginResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type PostApiV1AuthLoginResponse = PostApiV1AuthLoginResponses[keyof PostApiV1AuthLoginResponses];

export type PostApiV1AuthRefreshData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type PostApiV1AuthRefreshErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1AuthRefreshError = PostApiV1AuthRefreshErrors[keyof PostApiV1AuthRefreshErrors];

export type PostApiV1AuthRefreshResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type PostApiV1AuthRefreshResponse = PostApiV1AuthRefreshResponses[keyof PostApiV1AuthRefreshResponses];

export type PostApiV1AuthLogoutData = {
    body: LogoutRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type PostApiV1AuthLogoutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1AuthLogoutError = PostApiV1AuthLogoutErrors[keyof PostApiV1AuthLogoutErrors];

export type PostApiV1AuthLogoutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type PostApiV1AuthLogoutResponse = PostApiV1AuthLogoutResponses[keyof PostApiV1AuthLogoutResponses];

export type PostApiV1AuthPasswordResetData = {
    body: PasswordResetRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/password-reset';
};

export type PostApiV1AuthPasswordResetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1AuthPasswordResetError = PostApiV1AuthPasswordResetErrors[keyof PostApiV1AuthPasswordResetErrors];

export type PostApiV1AuthPasswordResetResponses = {
    /**
     * Successful Response
     */
    202: PasswordResetRequestResponse;
};

export type PostApiV1AuthPasswordResetResponse = PostApiV1AuthPasswordResetResponses[keyof PostApiV1AuthPasswordResetResponses];

export type PostApiV1AuthPasswordResetConfirmData = {
    body: PasswordResetConfirmRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/password-reset/confirm';
};

export type PostApiV1AuthPasswordResetConfirmErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1AuthPasswordResetConfirmError = PostApiV1AuthPasswordResetConfirmErrors[keyof PostApiV1AuthPasswordResetConfirmErrors];

export type PostApiV1AuthPasswordResetConfirmResponses = {
    /**
     * Successful Response
     */
    200: PasswordResetConfirmResponse;
};

export type PostApiV1AuthPasswordResetConfirmResponse = PostApiV1AuthPasswordResetConfirmResponses[keyof PostApiV1AuthPasswordResetConfirmResponses];

export type PostApiV1AuthChangePasswordData = {
    body: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/change-password';
};

export type PostApiV1AuthChangePasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1AuthChangePasswordError = PostApiV1AuthChangePasswordErrors[keyof PostApiV1AuthChangePasswordErrors];

export type PostApiV1AuthChangePasswordResponses = {
    /**
     * Successful Response
     */
    200: ChangePasswordResponse;
};

export type PostApiV1AuthChangePasswordResponse = PostApiV1AuthChangePasswordResponses[keyof PostApiV1AuthChangePasswordResponses];

export type GetApiV1AuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type GetApiV1AuthMeResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetApiV1AuthMeResponse = GetApiV1AuthMeResponses[keyof GetApiV1AuthMeResponses];

export type PatchApiV1AuthMeData = {
    body: UpdateProfileRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type PatchApiV1AuthMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchApiV1AuthMeError = PatchApiV1AuthMeErrors[keyof PatchApiV1AuthMeErrors];

export type PatchApiV1AuthMeResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type PatchApiV1AuthMeResponse = PatchApiV1AuthMeResponses[keyof PatchApiV1AuthMeResponses];

export type GetApiV1AuthOauthByProviderLoginData = {
    body?: never;
    path: {
        /**
         * Provider
         */
        provider: string;
    };
    query?: never;
    url: '/api/v1/auth/oauth/{provider}/login';
};

export type GetApiV1AuthOauthByProviderLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1AuthOauthByProviderLoginError = GetApiV1AuthOauthByProviderLoginErrors[keyof GetApiV1AuthOauthByProviderLoginErrors];

export type GetApiV1AuthOauthByProviderLoginResponses = {
    /**
     * Successful Response
     */
    200: OAuthLoginUrlResponse;
};

export type GetApiV1AuthOauthByProviderLoginResponse = GetApiV1AuthOauthByProviderLoginResponses[keyof GetApiV1AuthOauthByProviderLoginResponses];

export type GetApiV1AuthOauthByProviderCallbackData = {
    body?: never;
    path: {
        /**
         * Provider
         */
        provider: string;
    };
    query: {
        /**
         * Code
         *
         * Authorization code from provider
         */
        code: string;
        /**
         * State
         *
         * CSRF state nonce
         */
        state: string;
    };
    url: '/api/v1/auth/oauth/{provider}/callback';
};

export type GetApiV1AuthOauthByProviderCallbackErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1AuthOauthByProviderCallbackError = GetApiV1AuthOauthByProviderCallbackErrors[keyof GetApiV1AuthOauthByProviderCallbackErrors];

export type GetApiV1AuthOauthByProviderCallbackResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type GetApiV1AuthOauthByProviderCallbackResponse = GetApiV1AuthOauthByProviderCallbackResponses[keyof GetApiV1AuthOauthByProviderCallbackResponses];

export type PostApiV1ChatCompleteData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/api/v1/chat/complete';
};

export type PostApiV1ChatCompleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1ChatCompleteError = PostApiV1ChatCompleteErrors[keyof PostApiV1ChatCompleteErrors];

export type PostApiV1ChatCompleteResponses = {
    /**
     * Successful Response
     */
    200: ChatResponse;
};

export type PostApiV1ChatCompleteResponse = PostApiV1ChatCompleteResponses[keyof PostApiV1ChatCompleteResponses];

export type PostApiV1ChatStreamData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/api/v1/chat/stream';
};

export type PostApiV1ChatStreamErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1ChatStreamError = PostApiV1ChatStreamErrors[keyof PostApiV1ChatStreamErrors];

export type PostApiV1ChatStreamResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetApiV1ChatProviderData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/chat/provider';
};

export type GetApiV1ChatProviderResponses = {
    /**
     * Successful Response
     */
    200: ProviderInfoResponse;
};

export type GetApiV1ChatProviderResponse = GetApiV1ChatProviderResponses[keyof GetApiV1ChatProviderResponses];

export type GetApiV1ChatConversationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/chat/conversations';
};

export type GetApiV1ChatConversationsResponses = {
    /**
     * Response List Conversations Api V1 Chat Conversations Get
     *
     * Successful Response
     */
    200: Array<ConversationResponse>;
};

export type GetApiV1ChatConversationsResponse = GetApiV1ChatConversationsResponses[keyof GetApiV1ChatConversationsResponses];

export type PostApiV1ChatConversationsData = {
    body: ConversationCreate;
    path?: never;
    query?: never;
    url: '/api/v1/chat/conversations';
};

export type PostApiV1ChatConversationsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1ChatConversationsError = PostApiV1ChatConversationsErrors[keyof PostApiV1ChatConversationsErrors];

export type PostApiV1ChatConversationsResponses = {
    /**
     * Successful Response
     */
    201: ConversationResponse;
};

export type PostApiV1ChatConversationsResponse = PostApiV1ChatConversationsResponses[keyof PostApiV1ChatConversationsResponses];

export type GetApiV1ChatConversationsByConversationIdData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/chat/conversations/{conversation_id}';
};

export type GetApiV1ChatConversationsByConversationIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1ChatConversationsByConversationIdError = GetApiV1ChatConversationsByConversationIdErrors[keyof GetApiV1ChatConversationsByConversationIdErrors];

export type GetApiV1ChatConversationsByConversationIdResponses = {
    /**
     * Successful Response
     */
    200: ConversationResponse;
};

export type GetApiV1ChatConversationsByConversationIdResponse = GetApiV1ChatConversationsByConversationIdResponses[keyof GetApiV1ChatConversationsByConversationIdResponses];

export type GetApiV1ChatConversationsByConversationIdMessagesData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/chat/conversations/{conversation_id}/messages';
};

export type GetApiV1ChatConversationsByConversationIdMessagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1ChatConversationsByConversationIdMessagesError = GetApiV1ChatConversationsByConversationIdMessagesErrors[keyof GetApiV1ChatConversationsByConversationIdMessagesErrors];

export type GetApiV1ChatConversationsByConversationIdMessagesResponses = {
    /**
     * Response List Messages Api V1 Chat Conversations  Conversation Id  Messages Get
     *
     * Successful Response
     */
    200: Array<MessageResponse>;
};

export type GetApiV1ChatConversationsByConversationIdMessagesResponse = GetApiV1ChatConversationsByConversationIdMessagesResponses[keyof GetApiV1ChatConversationsByConversationIdMessagesResponses];

export type PostApiV1ChatConversationsByConversationIdMessagesData = {
    body: SendMessageRequest;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/chat/conversations/{conversation_id}/messages';
};

export type PostApiV1ChatConversationsByConversationIdMessagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1ChatConversationsByConversationIdMessagesError = PostApiV1ChatConversationsByConversationIdMessagesErrors[keyof PostApiV1ChatConversationsByConversationIdMessagesErrors];

export type PostApiV1ChatConversationsByConversationIdMessagesResponses = {
    /**
     * Response Send Message Api V1 Chat Conversations  Conversation Id  Messages Post
     *
     * Successful Response
     */
    200: unknown;
};

export type GetApiV1WorksByWorkIdChatConversationData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/chat/conversation';
};

export type GetApiV1WorksByWorkIdChatConversationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1WorksByWorkIdChatConversationError = GetApiV1WorksByWorkIdChatConversationErrors[keyof GetApiV1WorksByWorkIdChatConversationErrors];

export type GetApiV1WorksByWorkIdChatConversationResponses = {
    /**
     * Response Get Work Conversation Api V1 Works  Work Id  Chat Conversation Get
     *
     * Successful Response
     */
    200: ConversationResponse | null;
};

export type GetApiV1WorksByWorkIdChatConversationResponse = GetApiV1WorksByWorkIdChatConversationResponses[keyof GetApiV1WorksByWorkIdChatConversationResponses];

export type GetApiV1WorksByWorkIdChatConversationMessagesData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/chat/conversation/messages';
};

export type GetApiV1WorksByWorkIdChatConversationMessagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1WorksByWorkIdChatConversationMessagesError = GetApiV1WorksByWorkIdChatConversationMessagesErrors[keyof GetApiV1WorksByWorkIdChatConversationMessagesErrors];

export type GetApiV1WorksByWorkIdChatConversationMessagesResponses = {
    /**
     * Response Get Work Conversation Messages Api V1 Works  Work Id  Chat Conversation Messages Get
     *
     * Successful Response
     */
    200: Array<MessageResponse>;
};

export type GetApiV1WorksByWorkIdChatConversationMessagesResponse = GetApiV1WorksByWorkIdChatConversationMessagesResponses[keyof GetApiV1WorksByWorkIdChatConversationMessagesResponses];

export type PostApiV1WorksByWorkIdChatConversationsData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/chat/conversations';
};

export type PostApiV1WorksByWorkIdChatConversationsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1WorksByWorkIdChatConversationsError = PostApiV1WorksByWorkIdChatConversationsErrors[keyof PostApiV1WorksByWorkIdChatConversationsErrors];

export type PostApiV1WorksByWorkIdChatConversationsResponses = {
    /**
     * Successful Response
     */
    201: ConversationResponse;
};

export type PostApiV1WorksByWorkIdChatConversationsResponse = PostApiV1WorksByWorkIdChatConversationsResponses[keyof PostApiV1WorksByWorkIdChatConversationsResponses];

export type PostApiV1WorksByWorkIdChatMessagesData = {
    body: SendWorkChatMessageRequest;
    path: {
        /**
         * Work Id
         */
        work_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/chat/messages';
};

export type PostApiV1WorksByWorkIdChatMessagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1WorksByWorkIdChatMessagesError = PostApiV1WorksByWorkIdChatMessagesErrors[keyof PostApiV1WorksByWorkIdChatMessagesErrors];

export type PostApiV1WorksByWorkIdChatMessagesResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetApiV1WorksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/works';
};

export type GetApiV1WorksResponses = {
    /**
     * Response List Works Api V1 Works Get
     *
     * Successful Response
     */
    200: Array<WorkResponse>;
};

export type GetApiV1WorksResponse = GetApiV1WorksResponses[keyof GetApiV1WorksResponses];

export type PostApiV1WorksData = {
    body: WorkCreate;
    path?: never;
    query?: never;
    url: '/api/v1/works';
};

export type PostApiV1WorksErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1WorksError = PostApiV1WorksErrors[keyof PostApiV1WorksErrors];

export type PostApiV1WorksResponses = {
    /**
     * Successful Response
     */
    201: WorkResponse;
};

export type PostApiV1WorksResponse = PostApiV1WorksResponses[keyof PostApiV1WorksResponses];

export type DeleteApiV1WorksByWorkIdData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}';
};

export type DeleteApiV1WorksByWorkIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteApiV1WorksByWorkIdError = DeleteApiV1WorksByWorkIdErrors[keyof DeleteApiV1WorksByWorkIdErrors];

export type DeleteApiV1WorksByWorkIdResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteApiV1WorksByWorkIdResponse = DeleteApiV1WorksByWorkIdResponses[keyof DeleteApiV1WorksByWorkIdResponses];

export type GetApiV1WorksByWorkIdData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}';
};

export type GetApiV1WorksByWorkIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1WorksByWorkIdError = GetApiV1WorksByWorkIdErrors[keyof GetApiV1WorksByWorkIdErrors];

export type GetApiV1WorksByWorkIdResponses = {
    /**
     * Successful Response
     */
    200: WorkResponse;
};

export type GetApiV1WorksByWorkIdResponse = GetApiV1WorksByWorkIdResponses[keyof GetApiV1WorksByWorkIdResponses];

export type PatchApiV1WorksByWorkIdData = {
    body: WorkUpdate;
    path: {
        /**
         * Work Id
         */
        work_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}';
};

export type PatchApiV1WorksByWorkIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchApiV1WorksByWorkIdError = PatchApiV1WorksByWorkIdErrors[keyof PatchApiV1WorksByWorkIdErrors];

export type PatchApiV1WorksByWorkIdResponses = {
    /**
     * Successful Response
     */
    200: WorkResponse;
};

export type PatchApiV1WorksByWorkIdResponse = PatchApiV1WorksByWorkIdResponses[keyof PatchApiV1WorksByWorkIdResponses];

export type PostApiV1WorksByWorkIdBeatSheetData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/beat-sheet';
};

export type PostApiV1WorksByWorkIdBeatSheetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1WorksByWorkIdBeatSheetError = PostApiV1WorksByWorkIdBeatSheetErrors[keyof PostApiV1WorksByWorkIdBeatSheetErrors];

export type PostApiV1WorksByWorkIdBeatSheetResponses = {
    /**
     * Successful Response
     */
    200: BeatSheetResponse;
};

export type PostApiV1WorksByWorkIdBeatSheetResponse = PostApiV1WorksByWorkIdBeatSheetResponses[keyof PostApiV1WorksByWorkIdBeatSheetResponses];

export type GetApiV1WorksByWorkIdSynopsisData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/synopsis';
};

export type GetApiV1WorksByWorkIdSynopsisErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1WorksByWorkIdSynopsisError = GetApiV1WorksByWorkIdSynopsisErrors[keyof GetApiV1WorksByWorkIdSynopsisErrors];

export type GetApiV1WorksByWorkIdSynopsisResponses = {
    /**
     * Successful Response
     */
    200: SynopsisResponse;
};

export type GetApiV1WorksByWorkIdSynopsisResponse = GetApiV1WorksByWorkIdSynopsisResponses[keyof GetApiV1WorksByWorkIdSynopsisResponses];

export type PutApiV1WorksByWorkIdSynopsisData = {
    body: SynopsisUpdate;
    path: {
        /**
         * Work Id
         */
        work_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/synopsis';
};

export type PutApiV1WorksByWorkIdSynopsisErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutApiV1WorksByWorkIdSynopsisError = PutApiV1WorksByWorkIdSynopsisErrors[keyof PutApiV1WorksByWorkIdSynopsisErrors];

export type PutApiV1WorksByWorkIdSynopsisResponses = {
    /**
     * Successful Response
     */
    200: SynopsisResponse;
};

export type PutApiV1WorksByWorkIdSynopsisResponse = PutApiV1WorksByWorkIdSynopsisResponses[keyof PutApiV1WorksByWorkIdSynopsisResponses];

export type PostApiV1WorksByWorkIdSynopsisContinueData = {
    body: SynopsisContinueRequest;
    path: {
        /**
         * Work Id
         */
        work_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/synopsis/continue';
};

export type PostApiV1WorksByWorkIdSynopsisContinueErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1WorksByWorkIdSynopsisContinueError = PostApiV1WorksByWorkIdSynopsisContinueErrors[keyof PostApiV1WorksByWorkIdSynopsisContinueErrors];

export type PostApiV1WorksByWorkIdSynopsisContinueResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetApiV1WorksByWorkIdEpisodesData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/episodes';
};

export type GetApiV1WorksByWorkIdEpisodesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1WorksByWorkIdEpisodesError = GetApiV1WorksByWorkIdEpisodesErrors[keyof GetApiV1WorksByWorkIdEpisodesErrors];

export type GetApiV1WorksByWorkIdEpisodesResponses = {
    /**
     * Response List Episodes Api V1 Works  Work Id  Episodes Get
     *
     * Successful Response
     */
    200: Array<EpisodeResponse>;
};

export type GetApiV1WorksByWorkIdEpisodesResponse = GetApiV1WorksByWorkIdEpisodesResponses[keyof GetApiV1WorksByWorkIdEpisodesResponses];

export type PostApiV1WorksByWorkIdEpisodesData = {
    body: EpisodeCreate;
    path: {
        /**
         * Work Id
         */
        work_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/episodes';
};

export type PostApiV1WorksByWorkIdEpisodesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1WorksByWorkIdEpisodesError = PostApiV1WorksByWorkIdEpisodesErrors[keyof PostApiV1WorksByWorkIdEpisodesErrors];

export type PostApiV1WorksByWorkIdEpisodesResponses = {
    /**
     * Successful Response
     */
    201: EpisodeResponse;
};

export type PostApiV1WorksByWorkIdEpisodesResponse = PostApiV1WorksByWorkIdEpisodesResponses[keyof PostApiV1WorksByWorkIdEpisodesResponses];

export type PatchApiV1WorksByWorkIdEpisodesReorderData = {
    /**
     * Payload
     */
    body: Array<string>;
    path: {
        /**
         * Work Id
         */
        work_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/episodes/reorder';
};

export type PatchApiV1WorksByWorkIdEpisodesReorderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchApiV1WorksByWorkIdEpisodesReorderError = PatchApiV1WorksByWorkIdEpisodesReorderErrors[keyof PatchApiV1WorksByWorkIdEpisodesReorderErrors];

export type PatchApiV1WorksByWorkIdEpisodesReorderResponses = {
    /**
     * Response Reorder Episodes Api V1 Works  Work Id  Episodes Reorder Patch
     *
     * Successful Response
     */
    200: Array<EpisodeResponse>;
};

export type PatchApiV1WorksByWorkIdEpisodesReorderResponse = PatchApiV1WorksByWorkIdEpisodesReorderResponses[keyof PatchApiV1WorksByWorkIdEpisodesReorderResponses];

export type DeleteApiV1WorksByWorkIdEpisodesByEpisodeIdData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Episode Id
         */
        episode_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/episodes/{episode_id}';
};

export type DeleteApiV1WorksByWorkIdEpisodesByEpisodeIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteApiV1WorksByWorkIdEpisodesByEpisodeIdError = DeleteApiV1WorksByWorkIdEpisodesByEpisodeIdErrors[keyof DeleteApiV1WorksByWorkIdEpisodesByEpisodeIdErrors];

export type DeleteApiV1WorksByWorkIdEpisodesByEpisodeIdResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteApiV1WorksByWorkIdEpisodesByEpisodeIdResponse = DeleteApiV1WorksByWorkIdEpisodesByEpisodeIdResponses[keyof DeleteApiV1WorksByWorkIdEpisodesByEpisodeIdResponses];

export type GetApiV1WorksByWorkIdEpisodesByEpisodeIdData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Episode Id
         */
        episode_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/episodes/{episode_id}';
};

export type GetApiV1WorksByWorkIdEpisodesByEpisodeIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1WorksByWorkIdEpisodesByEpisodeIdError = GetApiV1WorksByWorkIdEpisodesByEpisodeIdErrors[keyof GetApiV1WorksByWorkIdEpisodesByEpisodeIdErrors];

export type GetApiV1WorksByWorkIdEpisodesByEpisodeIdResponses = {
    /**
     * Successful Response
     */
    200: EpisodeResponse;
};

export type GetApiV1WorksByWorkIdEpisodesByEpisodeIdResponse = GetApiV1WorksByWorkIdEpisodesByEpisodeIdResponses[keyof GetApiV1WorksByWorkIdEpisodesByEpisodeIdResponses];

export type PatchApiV1WorksByWorkIdEpisodesByEpisodeIdData = {
    body: EpisodeUpdate;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Episode Id
         */
        episode_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/episodes/{episode_id}';
};

export type PatchApiV1WorksByWorkIdEpisodesByEpisodeIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchApiV1WorksByWorkIdEpisodesByEpisodeIdError = PatchApiV1WorksByWorkIdEpisodesByEpisodeIdErrors[keyof PatchApiV1WorksByWorkIdEpisodesByEpisodeIdErrors];

export type PatchApiV1WorksByWorkIdEpisodesByEpisodeIdResponses = {
    /**
     * Successful Response
     */
    200: EpisodeResponse;
};

export type PatchApiV1WorksByWorkIdEpisodesByEpisodeIdResponse = PatchApiV1WorksByWorkIdEpisodesByEpisodeIdResponses[keyof PatchApiV1WorksByWorkIdEpisodesByEpisodeIdResponses];

export type GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Episode Id
         */
        episode_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/episodes/{episode_id}/chapters';
};

export type GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersError = GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersErrors[keyof GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersErrors];

export type GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersResponses = {
    /**
     * Response List Chapters Api V1 Works  Work Id  Episodes  Episode Id  Chapters Get
     *
     * Successful Response
     */
    200: Array<ChapterResponse>;
};

export type GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersResponse = GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersResponses[keyof GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersResponses];

export type PostApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersData = {
    body: ChapterCreate;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Episode Id
         */
        episode_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/episodes/{episode_id}/chapters';
};

export type PostApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersError = PostApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersErrors[keyof PostApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersErrors];

export type PostApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersResponses = {
    /**
     * Successful Response
     */
    201: ChapterResponse;
};

export type PostApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersResponse = PostApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersResponses[keyof PostApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersResponses];

export type PatchApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersReorderData = {
    /**
     * Payload
     */
    body: Array<string>;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Episode Id
         */
        episode_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/episodes/{episode_id}/chapters/reorder';
};

export type PatchApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersReorderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersReorderError = PatchApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersReorderErrors[keyof PatchApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersReorderErrors];

export type PatchApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersReorderResponses = {
    /**
     * Response Reorder Chapters Api V1 Works  Work Id  Episodes  Episode Id  Chapters Reorder Patch
     *
     * Successful Response
     */
    200: Array<ChapterResponse>;
};

export type PatchApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersReorderResponse = PatchApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersReorderResponses[keyof PatchApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersReorderResponses];

export type DeleteApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Episode Id
         */
        episode_id: string;
        /**
         * Chapter Id
         */
        chapter_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/episodes/{episode_id}/chapters/{chapter_id}';
};

export type DeleteApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdError = DeleteApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdErrors[keyof DeleteApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdErrors];

export type DeleteApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdResponse = DeleteApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdResponses[keyof DeleteApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdResponses];

export type GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Episode Id
         */
        episode_id: string;
        /**
         * Chapter Id
         */
        chapter_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/episodes/{episode_id}/chapters/{chapter_id}';
};

export type GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdError = GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdErrors[keyof GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdErrors];

export type GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdResponses = {
    /**
     * Successful Response
     */
    200: ChapterResponse;
};

export type GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdResponse = GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdResponses[keyof GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdResponses];

export type PatchApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdData = {
    body: ChapterUpdate;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Episode Id
         */
        episode_id: string;
        /**
         * Chapter Id
         */
        chapter_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/episodes/{episode_id}/chapters/{chapter_id}';
};

export type PatchApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdError = PatchApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdErrors[keyof PatchApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdErrors];

export type PatchApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdResponses = {
    /**
     * Successful Response
     */
    200: ChapterResponse;
};

export type PatchApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdResponse = PatchApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdResponses[keyof PatchApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdResponses];

export type GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdVersionsData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Episode Id
         */
        episode_id: string;
        /**
         * Chapter Id
         */
        chapter_id: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/v1/works/{work_id}/episodes/{episode_id}/chapters/{chapter_id}/versions';
};

export type GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdVersionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdVersionsError = GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdVersionsErrors[keyof GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdVersionsErrors];

export type GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdVersionsResponses = {
    /**
     * Successful Response
     */
    200: ChapterVersionListResponse;
};

export type GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdVersionsResponse = GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdVersionsResponses[keyof GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdVersionsResponses];

export type GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdVersionsByVersionIdData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Episode Id
         */
        episode_id: string;
        /**
         * Chapter Id
         */
        chapter_id: string;
        /**
         * Version Id
         */
        version_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/episodes/{episode_id}/chapters/{chapter_id}/versions/{version_id}';
};

export type GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdVersionsByVersionIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdVersionsByVersionIdError = GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdVersionsByVersionIdErrors[keyof GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdVersionsByVersionIdErrors];

export type GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdVersionsByVersionIdResponses = {
    /**
     * Successful Response
     */
    200: ChapterVersionDetailResponse;
};

export type GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdVersionsByVersionIdResponse = GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdVersionsByVersionIdResponses[keyof GetApiV1WorksByWorkIdEpisodesByEpisodeIdChaptersByChapterIdVersionsByVersionIdResponses];

export type GetApiV1WorksByWorkIdExportData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/export';
};

export type GetApiV1WorksByWorkIdExportErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1WorksByWorkIdExportError = GetApiV1WorksByWorkIdExportErrors[keyof GetApiV1WorksByWorkIdExportErrors];

export type GetApiV1WorksByWorkIdExportResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetApiV1WorksByWorkIdEntitiesData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/entities';
};

export type GetApiV1WorksByWorkIdEntitiesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1WorksByWorkIdEntitiesError = GetApiV1WorksByWorkIdEntitiesErrors[keyof GetApiV1WorksByWorkIdEntitiesErrors];

export type GetApiV1WorksByWorkIdEntitiesResponses = {
    /**
     * Response List Entities Api V1 Works  Work Id  Entities Get
     *
     * Successful Response
     */
    200: Array<EntityResponse>;
};

export type GetApiV1WorksByWorkIdEntitiesResponse = GetApiV1WorksByWorkIdEntitiesResponses[keyof GetApiV1WorksByWorkIdEntitiesResponses];

export type PostApiV1WorksByWorkIdEntitiesData = {
    body: EntityCreate;
    path: {
        /**
         * Work Id
         */
        work_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/entities';
};

export type PostApiV1WorksByWorkIdEntitiesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1WorksByWorkIdEntitiesError = PostApiV1WorksByWorkIdEntitiesErrors[keyof PostApiV1WorksByWorkIdEntitiesErrors];

export type PostApiV1WorksByWorkIdEntitiesResponses = {
    /**
     * Successful Response
     */
    201: EntityResponse;
};

export type PostApiV1WorksByWorkIdEntitiesResponse = PostApiV1WorksByWorkIdEntitiesResponses[keyof PostApiV1WorksByWorkIdEntitiesResponses];

export type DeleteApiV1WorksByWorkIdEntitiesByEntityIdData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Entity Id
         */
        entity_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/entities/{entity_id}';
};

export type DeleteApiV1WorksByWorkIdEntitiesByEntityIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteApiV1WorksByWorkIdEntitiesByEntityIdError = DeleteApiV1WorksByWorkIdEntitiesByEntityIdErrors[keyof DeleteApiV1WorksByWorkIdEntitiesByEntityIdErrors];

export type DeleteApiV1WorksByWorkIdEntitiesByEntityIdResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteApiV1WorksByWorkIdEntitiesByEntityIdResponse = DeleteApiV1WorksByWorkIdEntitiesByEntityIdResponses[keyof DeleteApiV1WorksByWorkIdEntitiesByEntityIdResponses];

export type GetApiV1WorksByWorkIdEntitiesByEntityIdData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Entity Id
         */
        entity_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/entities/{entity_id}';
};

export type GetApiV1WorksByWorkIdEntitiesByEntityIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1WorksByWorkIdEntitiesByEntityIdError = GetApiV1WorksByWorkIdEntitiesByEntityIdErrors[keyof GetApiV1WorksByWorkIdEntitiesByEntityIdErrors];

export type GetApiV1WorksByWorkIdEntitiesByEntityIdResponses = {
    /**
     * Successful Response
     */
    200: EntityResponse;
};

export type GetApiV1WorksByWorkIdEntitiesByEntityIdResponse = GetApiV1WorksByWorkIdEntitiesByEntityIdResponses[keyof GetApiV1WorksByWorkIdEntitiesByEntityIdResponses];

export type PatchApiV1WorksByWorkIdEntitiesByEntityIdData = {
    body: EntityUpdate;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Entity Id
         */
        entity_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/entities/{entity_id}';
};

export type PatchApiV1WorksByWorkIdEntitiesByEntityIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchApiV1WorksByWorkIdEntitiesByEntityIdError = PatchApiV1WorksByWorkIdEntitiesByEntityIdErrors[keyof PatchApiV1WorksByWorkIdEntitiesByEntityIdErrors];

export type PatchApiV1WorksByWorkIdEntitiesByEntityIdResponses = {
    /**
     * Successful Response
     */
    200: EntityResponse;
};

export type PatchApiV1WorksByWorkIdEntitiesByEntityIdResponse = PatchApiV1WorksByWorkIdEntitiesByEntityIdResponses[keyof PatchApiV1WorksByWorkIdEntitiesByEntityIdResponses];

export type GetApiV1ArtStylesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/art-styles';
};

export type GetApiV1ArtStylesResponses = {
    /**
     * Response List Art Styles Endpoint Api V1 Art Styles Get
     *
     * Successful Response
     */
    200: Array<ArtStyleResponse>;
};

export type GetApiV1ArtStylesResponse = GetApiV1ArtStylesResponses[keyof GetApiV1ArtStylesResponses];

export type GetApiV1ArtStylesByStyleIdSamplesByEntityTypeData = {
    body?: never;
    path: {
        /**
         * Style Id
         */
        style_id: string;
        /**
         * Entity Type
         */
        entity_type: 'character' | 'location' | 'event' | 'item';
    };
    query?: never;
    url: '/api/v1/art-styles/{style_id}/samples/{entity_type}';
};

export type GetApiV1ArtStylesByStyleIdSamplesByEntityTypeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1ArtStylesByStyleIdSamplesByEntityTypeError = GetApiV1ArtStylesByStyleIdSamplesByEntityTypeErrors[keyof GetApiV1ArtStylesByStyleIdSamplesByEntityTypeErrors];

export type GetApiV1ArtStylesByStyleIdSamplesByEntityTypeResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetApiV1WorksByWorkIdArtStyleData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/art-style';
};

export type GetApiV1WorksByWorkIdArtStyleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1WorksByWorkIdArtStyleError = GetApiV1WorksByWorkIdArtStyleErrors[keyof GetApiV1WorksByWorkIdArtStyleErrors];

export type GetApiV1WorksByWorkIdArtStyleResponses = {
    /**
     * Successful Response
     */
    200: WorkArtStyleResponse;
};

export type GetApiV1WorksByWorkIdArtStyleResponse = GetApiV1WorksByWorkIdArtStyleResponses[keyof GetApiV1WorksByWorkIdArtStyleResponses];

export type PutApiV1WorksByWorkIdArtStyleData = {
    body: ArtStyleUpdateRequest;
    path: {
        /**
         * Work Id
         */
        work_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/art-style';
};

export type PutApiV1WorksByWorkIdArtStyleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutApiV1WorksByWorkIdArtStyleError = PutApiV1WorksByWorkIdArtStyleErrors[keyof PutApiV1WorksByWorkIdArtStyleErrors];

export type PutApiV1WorksByWorkIdArtStyleResponses = {
    /**
     * Successful Response
     */
    200: WorkArtStyleResponse;
};

export type PutApiV1WorksByWorkIdArtStyleResponse = PutApiV1WorksByWorkIdArtStyleResponses[keyof PutApiV1WorksByWorkIdArtStyleResponses];

export type GetApiV1WorksByWorkIdImagesByImageIdData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Image Id
         */
        image_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/images/{image_id}';
};

export type GetApiV1WorksByWorkIdImagesByImageIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1WorksByWorkIdImagesByImageIdError = GetApiV1WorksByWorkIdImagesByImageIdErrors[keyof GetApiV1WorksByWorkIdImagesByImageIdErrors];

export type GetApiV1WorksByWorkIdImagesByImageIdResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PatchApiV1WorksByWorkIdImagesByImageIdData = {
    body: UpdateEntityImageRequest;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Image Id
         */
        image_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/images/{image_id}';
};

export type PatchApiV1WorksByWorkIdImagesByImageIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchApiV1WorksByWorkIdImagesByImageIdError = PatchApiV1WorksByWorkIdImagesByImageIdErrors[keyof PatchApiV1WorksByWorkIdImagesByImageIdErrors];

export type PatchApiV1WorksByWorkIdImagesByImageIdResponses = {
    /**
     * Successful Response
     */
    200: EntityImageResponse;
};

export type PatchApiV1WorksByWorkIdImagesByImageIdResponse = PatchApiV1WorksByWorkIdImagesByImageIdResponses[keyof PatchApiV1WorksByWorkIdImagesByImageIdResponses];

export type GetApiV1WorksByWorkIdEntitiesByEntityIdImagesData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Entity Id
         */
        entity_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/entities/{entity_id}/images';
};

export type GetApiV1WorksByWorkIdEntitiesByEntityIdImagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1WorksByWorkIdEntitiesByEntityIdImagesError = GetApiV1WorksByWorkIdEntitiesByEntityIdImagesErrors[keyof GetApiV1WorksByWorkIdEntitiesByEntityIdImagesErrors];

export type GetApiV1WorksByWorkIdEntitiesByEntityIdImagesResponses = {
    /**
     * Response List Entity Images Api V1 Works  Work Id  Entities  Entity Id  Images Get
     *
     * Successful Response
     */
    200: Array<EntityImageResponse>;
};

export type GetApiV1WorksByWorkIdEntitiesByEntityIdImagesResponse = GetApiV1WorksByWorkIdEntitiesByEntityIdImagesResponses[keyof GetApiV1WorksByWorkIdEntitiesByEntityIdImagesResponses];

export type PostApiV1WorksByWorkIdEntitiesByEntityIdImagesData = {
    body: GenerateEntityImageRequest;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Entity Id
         */
        entity_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/entities/{entity_id}/images';
};

export type PostApiV1WorksByWorkIdEntitiesByEntityIdImagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1WorksByWorkIdEntitiesByEntityIdImagesError = PostApiV1WorksByWorkIdEntitiesByEntityIdImagesErrors[keyof PostApiV1WorksByWorkIdEntitiesByEntityIdImagesErrors];

export type PostApiV1WorksByWorkIdEntitiesByEntityIdImagesResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetApiV1WorksByWorkIdEntitiesByEntityIdTimelineStatesData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Entity Id
         */
        entity_id: string;
    };
    query?: {
        /**
         * Up To Chapter Id
         */
        up_to_chapter_id?: string | null;
    };
    url: '/api/v1/works/{work_id}/entities/{entity_id}/timeline-states';
};

export type GetApiV1WorksByWorkIdEntitiesByEntityIdTimelineStatesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1WorksByWorkIdEntitiesByEntityIdTimelineStatesError = GetApiV1WorksByWorkIdEntitiesByEntityIdTimelineStatesErrors[keyof GetApiV1WorksByWorkIdEntitiesByEntityIdTimelineStatesErrors];

export type GetApiV1WorksByWorkIdEntitiesByEntityIdTimelineStatesResponses = {
    /**
     * Response List Timeline States Api V1 Works  Work Id  Entities  Entity Id  Timeline States Get
     *
     * Successful Response
     */
    200: Array<TimelineStateResponse>;
};

export type GetApiV1WorksByWorkIdEntitiesByEntityIdTimelineStatesResponse = GetApiV1WorksByWorkIdEntitiesByEntityIdTimelineStatesResponses[keyof GetApiV1WorksByWorkIdEntitiesByEntityIdTimelineStatesResponses];

export type PostApiV1WorksByWorkIdEntitiesByEntityIdTimelineStatesData = {
    body: TimelineStateCreate;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Entity Id
         */
        entity_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/entities/{entity_id}/timeline-states';
};

export type PostApiV1WorksByWorkIdEntitiesByEntityIdTimelineStatesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1WorksByWorkIdEntitiesByEntityIdTimelineStatesError = PostApiV1WorksByWorkIdEntitiesByEntityIdTimelineStatesErrors[keyof PostApiV1WorksByWorkIdEntitiesByEntityIdTimelineStatesErrors];

export type PostApiV1WorksByWorkIdEntitiesByEntityIdTimelineStatesResponses = {
    /**
     * Successful Response
     */
    201: TimelineStateResponse;
};

export type PostApiV1WorksByWorkIdEntitiesByEntityIdTimelineStatesResponse = PostApiV1WorksByWorkIdEntitiesByEntityIdTimelineStatesResponses[keyof PostApiV1WorksByWorkIdEntitiesByEntityIdTimelineStatesResponses];

export type GetApiV1WorksByWorkIdChaptersByChapterIdLinksData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Chapter Id
         */
        chapter_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/chapters/{chapter_id}/links';
};

export type GetApiV1WorksByWorkIdChaptersByChapterIdLinksErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1WorksByWorkIdChaptersByChapterIdLinksError = GetApiV1WorksByWorkIdChaptersByChapterIdLinksErrors[keyof GetApiV1WorksByWorkIdChaptersByChapterIdLinksErrors];

export type GetApiV1WorksByWorkIdChaptersByChapterIdLinksResponses = {
    /**
     * Response List Links Api V1 Works  Work Id  Chapters  Chapter Id  Links Get
     *
     * Successful Response
     */
    200: Array<SceneEntityLinkResponse>;
};

export type GetApiV1WorksByWorkIdChaptersByChapterIdLinksResponse = GetApiV1WorksByWorkIdChaptersByChapterIdLinksResponses[keyof GetApiV1WorksByWorkIdChaptersByChapterIdLinksResponses];

export type PostApiV1WorksByWorkIdChaptersByChapterIdLinksData = {
    body: SceneEntityLinkCreate;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Chapter Id
         */
        chapter_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/chapters/{chapter_id}/links';
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdLinksErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdLinksError = PostApiV1WorksByWorkIdChaptersByChapterIdLinksErrors[keyof PostApiV1WorksByWorkIdChaptersByChapterIdLinksErrors];

export type PostApiV1WorksByWorkIdChaptersByChapterIdLinksResponses = {
    /**
     * Successful Response
     */
    201: SceneEntityLinkResponse;
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdLinksResponse = PostApiV1WorksByWorkIdChaptersByChapterIdLinksResponses[keyof PostApiV1WorksByWorkIdChaptersByChapterIdLinksResponses];

export type DeleteApiV1WorksByWorkIdChaptersByChapterIdLinksByEntityIdData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Chapter Id
         */
        chapter_id: string;
        /**
         * Entity Id
         */
        entity_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/chapters/{chapter_id}/links/{entity_id}';
};

export type DeleteApiV1WorksByWorkIdChaptersByChapterIdLinksByEntityIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteApiV1WorksByWorkIdChaptersByChapterIdLinksByEntityIdError = DeleteApiV1WorksByWorkIdChaptersByChapterIdLinksByEntityIdErrors[keyof DeleteApiV1WorksByWorkIdChaptersByChapterIdLinksByEntityIdErrors];

export type DeleteApiV1WorksByWorkIdChaptersByChapterIdLinksByEntityIdResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteApiV1WorksByWorkIdChaptersByChapterIdLinksByEntityIdResponse = DeleteApiV1WorksByWorkIdChaptersByChapterIdLinksByEntityIdResponses[keyof DeleteApiV1WorksByWorkIdChaptersByChapterIdLinksByEntityIdResponses];

export type GetApiV1WorksByWorkIdChaptersByChapterIdMemoryData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Chapter Id
         */
        chapter_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/chapters/{chapter_id}/memory';
};

export type GetApiV1WorksByWorkIdChaptersByChapterIdMemoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1WorksByWorkIdChaptersByChapterIdMemoryError = GetApiV1WorksByWorkIdChaptersByChapterIdMemoryErrors[keyof GetApiV1WorksByWorkIdChaptersByChapterIdMemoryErrors];

export type GetApiV1WorksByWorkIdChaptersByChapterIdMemoryResponses = {
    /**
     * Response Search Memory Api V1 Works  Work Id  Chapters  Chapter Id  Memory Get
     *
     * Successful Response
     */
    200: Array<MemoryItemResponse>;
};

export type GetApiV1WorksByWorkIdChaptersByChapterIdMemoryResponse = GetApiV1WorksByWorkIdChaptersByChapterIdMemoryResponses[keyof GetApiV1WorksByWorkIdChaptersByChapterIdMemoryResponses];

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistContinueData = {
    body: ContinueRequest;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Chapter Id
         */
        chapter_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/chapters/{chapter_id}/assist/continue';
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistContinueErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistContinueError = PostApiV1WorksByWorkIdChaptersByChapterIdAssistContinueErrors[keyof PostApiV1WorksByWorkIdChaptersByChapterIdAssistContinueErrors];

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistContinueResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistInfillData = {
    body: InfillRequest;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Chapter Id
         */
        chapter_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/chapters/{chapter_id}/assist/infill';
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistInfillErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistInfillError = PostApiV1WorksByWorkIdChaptersByChapterIdAssistInfillErrors[keyof PostApiV1WorksByWorkIdChaptersByChapterIdAssistInfillErrors];

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistInfillResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistDialogueData = {
    body: DialogueRequest;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Chapter Id
         */
        chapter_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/chapters/{chapter_id}/assist/dialogue';
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistDialogueErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistDialogueError = PostApiV1WorksByWorkIdChaptersByChapterIdAssistDialogueErrors[keyof PostApiV1WorksByWorkIdChaptersByChapterIdAssistDialogueErrors];

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistDialogueResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistStyleData = {
    body: StyleRequest;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Chapter Id
         */
        chapter_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/chapters/{chapter_id}/assist/style';
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistStyleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistStyleError = PostApiV1WorksByWorkIdChaptersByChapterIdAssistStyleErrors[keyof PostApiV1WorksByWorkIdChaptersByChapterIdAssistStyleErrors];

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistStyleResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistCorrectData = {
    body: CorrectRequest;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Chapter Id
         */
        chapter_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/chapters/{chapter_id}/assist/correct';
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistCorrectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistCorrectError = PostApiV1WorksByWorkIdChaptersByChapterIdAssistCorrectErrors[keyof PostApiV1WorksByWorkIdChaptersByChapterIdAssistCorrectErrors];

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistCorrectResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistTitleData = {
    body: TitleRequest;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Chapter Id
         */
        chapter_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/chapters/{chapter_id}/assist/title';
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistTitleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistTitleError = PostApiV1WorksByWorkIdChaptersByChapterIdAssistTitleErrors[keyof PostApiV1WorksByWorkIdChaptersByChapterIdAssistTitleErrors];

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistTitleResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistSummaryData = {
    body: SummaryRequest;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Chapter Id
         */
        chapter_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/chapters/{chapter_id}/assist/summary';
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistSummaryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistSummaryError = PostApiV1WorksByWorkIdChaptersByChapterIdAssistSummaryErrors[keyof PostApiV1WorksByWorkIdChaptersByChapterIdAssistSummaryErrors];

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistSummaryResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistDraftData = {
    body: DraftRequest;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Chapter Id
         */
        chapter_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/chapters/{chapter_id}/assist/draft';
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistDraftErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistDraftError = PostApiV1WorksByWorkIdChaptersByChapterIdAssistDraftErrors[keyof PostApiV1WorksByWorkIdChaptersByChapterIdAssistDraftErrors];

export type PostApiV1WorksByWorkIdChaptersByChapterIdAssistDraftResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdExtractUpdatesData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Chapter Id
         */
        chapter_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/chapters/{chapter_id}/extract-updates';
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdExtractUpdatesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdExtractUpdatesError = PostApiV1WorksByWorkIdChaptersByChapterIdExtractUpdatesErrors[keyof PostApiV1WorksByWorkIdChaptersByChapterIdExtractUpdatesErrors];

export type PostApiV1WorksByWorkIdChaptersByChapterIdExtractUpdatesResponses = {
    /**
     * Successful Response
     */
    200: ExtractUpdatesResponse;
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdExtractUpdatesResponse = PostApiV1WorksByWorkIdChaptersByChapterIdExtractUpdatesResponses[keyof PostApiV1WorksByWorkIdChaptersByChapterIdExtractUpdatesResponses];

export type GetApiV1WorksByWorkIdChaptersByChapterIdUpdateSuggestionsData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Chapter Id
         */
        chapter_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/chapters/{chapter_id}/update-suggestions';
};

export type GetApiV1WorksByWorkIdChaptersByChapterIdUpdateSuggestionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1WorksByWorkIdChaptersByChapterIdUpdateSuggestionsError = GetApiV1WorksByWorkIdChaptersByChapterIdUpdateSuggestionsErrors[keyof GetApiV1WorksByWorkIdChaptersByChapterIdUpdateSuggestionsErrors];

export type GetApiV1WorksByWorkIdChaptersByChapterIdUpdateSuggestionsResponses = {
    /**
     * Response List Update Suggestions Api V1 Works  Work Id  Chapters  Chapter Id  Update Suggestions Get
     *
     * Successful Response
     */
    200: Array<UpdateSuggestionResponse>;
};

export type GetApiV1WorksByWorkIdChaptersByChapterIdUpdateSuggestionsResponse = GetApiV1WorksByWorkIdChaptersByChapterIdUpdateSuggestionsResponses[keyof GetApiV1WorksByWorkIdChaptersByChapterIdUpdateSuggestionsResponses];

export type PostApiV1WorksByWorkIdChaptersByChapterIdUpdateSuggestionsBySuggestionIdApproveData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Chapter Id
         */
        chapter_id: string;
        /**
         * Suggestion Id
         */
        suggestion_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/chapters/{chapter_id}/update-suggestions/{suggestion_id}/approve';
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdUpdateSuggestionsBySuggestionIdApproveErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdUpdateSuggestionsBySuggestionIdApproveError = PostApiV1WorksByWorkIdChaptersByChapterIdUpdateSuggestionsBySuggestionIdApproveErrors[keyof PostApiV1WorksByWorkIdChaptersByChapterIdUpdateSuggestionsBySuggestionIdApproveErrors];

export type PostApiV1WorksByWorkIdChaptersByChapterIdUpdateSuggestionsBySuggestionIdApproveResponses = {
    /**
     * Successful Response
     */
    200: UpdateSuggestionResponse;
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdUpdateSuggestionsBySuggestionIdApproveResponse = PostApiV1WorksByWorkIdChaptersByChapterIdUpdateSuggestionsBySuggestionIdApproveResponses[keyof PostApiV1WorksByWorkIdChaptersByChapterIdUpdateSuggestionsBySuggestionIdApproveResponses];

export type PostApiV1WorksByWorkIdChaptersByChapterIdUpdateSuggestionsBySuggestionIdRejectData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
        /**
         * Chapter Id
         */
        chapter_id: string;
        /**
         * Suggestion Id
         */
        suggestion_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/chapters/{chapter_id}/update-suggestions/{suggestion_id}/reject';
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdUpdateSuggestionsBySuggestionIdRejectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdUpdateSuggestionsBySuggestionIdRejectError = PostApiV1WorksByWorkIdChaptersByChapterIdUpdateSuggestionsBySuggestionIdRejectErrors[keyof PostApiV1WorksByWorkIdChaptersByChapterIdUpdateSuggestionsBySuggestionIdRejectErrors];

export type PostApiV1WorksByWorkIdChaptersByChapterIdUpdateSuggestionsBySuggestionIdRejectResponses = {
    /**
     * Successful Response
     */
    200: UpdateSuggestionResponse;
};

export type PostApiV1WorksByWorkIdChaptersByChapterIdUpdateSuggestionsBySuggestionIdRejectResponse = PostApiV1WorksByWorkIdChaptersByChapterIdUpdateSuggestionsBySuggestionIdRejectResponses[keyof PostApiV1WorksByWorkIdChaptersByChapterIdUpdateSuggestionsBySuggestionIdRejectResponses];

export type GetApiV1WorksByWorkIdConflictsData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
    };
    query?: never;
    url: '/api/v1/works/{work_id}/conflicts';
};

export type GetApiV1WorksByWorkIdConflictsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1WorksByWorkIdConflictsError = GetApiV1WorksByWorkIdConflictsErrors[keyof GetApiV1WorksByWorkIdConflictsErrors];

export type GetApiV1WorksByWorkIdConflictsResponses = {
    /**
     * Response List Conflicts Api V1 Works  Work Id  Conflicts Get
     *
     * Successful Response
     */
    200: Array<ConflictResponse>;
};

export type GetApiV1WorksByWorkIdConflictsResponse = GetApiV1WorksByWorkIdConflictsResponses[keyof GetApiV1WorksByWorkIdConflictsResponses];

export type GetApiV1WorksByWorkIdRelationshipsData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: string;
    };
    query?: {
        /**
         * Up To Chapter Id
         */
        up_to_chapter_id?: string | null;
    };
    url: '/api/v1/works/{work_id}/relationships';
};

export type GetApiV1WorksByWorkIdRelationshipsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1WorksByWorkIdRelationshipsError = GetApiV1WorksByWorkIdRelationshipsErrors[keyof GetApiV1WorksByWorkIdRelationshipsErrors];

export type GetApiV1WorksByWorkIdRelationshipsResponses = {
    /**
     * Successful Response
     */
    200: RelationshipGraphResponse;
};

export type GetApiV1WorksByWorkIdRelationshipsResponse = GetApiV1WorksByWorkIdRelationshipsResponses[keyof GetApiV1WorksByWorkIdRelationshipsResponses];
