// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8080' | (string & {});
};

export type PostUpdateRequest = {
    title: string;
    content: string;
};

export type ApiResponsePostResponse = {
    data?: PostResponse;
};

export type PostResponse = {
    id?: string;
    boardId?: string;
    authorId?: string;
    title?: string;
    content?: string;
    createdAt?: string;
};

export type ReactionSetRequest = {
    type: 'LIKE' | 'DISLIKE';
};

export type ApiResponseVoid = {
    data?: unknown;
};

export type SampleCreateRequest = {
    title: string;
};

export type ApiResponseSampleResponse = {
    data?: SampleResponse;
};

export type SampleResponse = {
    id?: string;
    title?: string;
    createdAt?: string;
};

export type CommentCreateRequest = {
    content: string;
    parentCommentId?: string;
};

export type ApiResponseCommentResponse = {
    data?: CommentResponse;
};

export type CommentResponse = {
    id?: string;
    postId?: string;
    parentCommentId?: string;
    authorId?: string;
    content?: string;
    createdAt?: string;
};

export type BoardCreateRequest = {
    name: string;
};

export type ApiResponseBoardResponse = {
    data?: BoardResponse;
};

export type BoardResponse = {
    id?: string;
    name?: string;
    createdAt?: string;
};

export type PostCreateRequest = {
    title: string;
    content: string;
};

export type SignupRequest = {
    email: string;
    password: string;
};

export type RefreshRequest = {
    refreshToken: string;
};

export type ApiResponseTokenResponse = {
    data?: TokenResponse;
};

export type TokenResponse = {
    accessToken?: string;
    refreshToken?: string;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type ApiResponsePasswordResetResponse = {
    data?: PasswordResetResponse;
};

export type PasswordResetResponse = {
    temporaryPassword?: string;
};

export type ApiResponseListSampleResponse = {
    data?: Array<SampleResponse>;
};

export type ApiResponsePageResponseCommentListItem = {
    data?: PageResponseCommentListItem;
};

export type CommentListItem = {
    id?: string;
    parentCommentId?: string;
    authorId?: string;
    content?: string;
    createdAt?: string;
    likeCount?: number;
    dislikeCount?: number;
};

export type PageResponseCommentListItem = {
    content?: Array<CommentListItem>;
    totalElements?: number;
    totalPages?: number;
    pageNumber?: number;
    pageSize?: number;
    hasNext?: boolean;
    hasPrevious?: boolean;
};

export type ApiResponsePageResponsePostListItem = {
    data?: PageResponsePostListItem;
};

export type PageResponsePostListItem = {
    content?: Array<PostListItem>;
    totalElements?: number;
    totalPages?: number;
    pageNumber?: number;
    pageSize?: number;
    hasNext?: boolean;
    hasPrevious?: boolean;
};

export type PostListItem = {
    id?: string;
    title?: string;
    authorId?: string;
    createdAt?: string;
    likeCount?: number;
    dislikeCount?: number;
};

export type AdminUserResponse = {
    id?: string;
    email?: string;
    role?: 'USER' | 'ADMIN';
    createdAt?: string;
};

export type ApiResponsePageResponseAdminUserResponse = {
    data?: PageResponseAdminUserResponse;
};

export type PageResponseAdminUserResponse = {
    content?: Array<AdminUserResponse>;
    totalElements?: number;
    totalPages?: number;
    pageNumber?: number;
    pageSize?: number;
    hasNext?: boolean;
    hasPrevious?: boolean;
};

export type ApiResponseAdminUserResponse = {
    data?: AdminUserResponse;
};

export type DeletePostsByPostIdData = {
    body?: never;
    path: {
        postId: string;
    };
    query?: never;
    url: '/posts/{postId}';
};

export type DeletePostsByPostIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetPostsByPostIdData = {
    body?: never;
    path: {
        postId: string;
    };
    query?: never;
    url: '/posts/{postId}';
};

export type GetPostsByPostIdResponses = {
    /**
     * OK
     */
    200: ApiResponsePostResponse;
};

export type GetPostsByPostIdResponse = GetPostsByPostIdResponses[keyof GetPostsByPostIdResponses];

export type PutPostsByPostIdData = {
    body: PostUpdateRequest;
    path: {
        postId: string;
    };
    query?: never;
    url: '/posts/{postId}';
};

export type PutPostsByPostIdResponses = {
    /**
     * OK
     */
    200: ApiResponsePostResponse;
};

export type PutPostsByPostIdResponse = PutPostsByPostIdResponses[keyof PutPostsByPostIdResponses];

export type DeletePostsByPostIdReactionsData = {
    body?: never;
    path: {
        postId: string;
    };
    query?: never;
    url: '/posts/{postId}/reactions';
};

export type DeletePostsByPostIdReactionsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutPostsByPostIdReactionsData = {
    body: ReactionSetRequest;
    path: {
        postId: string;
    };
    query?: never;
    url: '/posts/{postId}/reactions';
};

export type PutPostsByPostIdReactionsResponses = {
    /**
     * OK
     */
    200: ApiResponseVoid;
};

export type PutPostsByPostIdReactionsResponse = PutPostsByPostIdReactionsResponses[keyof PutPostsByPostIdReactionsResponses];

export type DeleteCommentsByCommentIdReactionsData = {
    body?: never;
    path: {
        commentId: string;
    };
    query?: never;
    url: '/comments/{commentId}/reactions';
};

export type DeleteCommentsByCommentIdReactionsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutCommentsByCommentIdReactionsData = {
    body: ReactionSetRequest;
    path: {
        commentId: string;
    };
    query?: never;
    url: '/comments/{commentId}/reactions';
};

export type PutCommentsByCommentIdReactionsResponses = {
    /**
     * OK
     */
    200: ApiResponseVoid;
};

export type PutCommentsByCommentIdReactionsResponse = PutCommentsByCommentIdReactionsResponses[keyof PutCommentsByCommentIdReactionsResponses];

export type GetSamplesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/samples';
};

export type GetSamplesResponses = {
    /**
     * OK
     */
    200: ApiResponseListSampleResponse;
};

export type GetSamplesResponse = GetSamplesResponses[keyof GetSamplesResponses];

export type PostSamplesData = {
    body: SampleCreateRequest;
    path?: never;
    query?: never;
    url: '/samples';
};

export type PostSamplesResponses = {
    /**
     * Created
     */
    201: ApiResponseSampleResponse;
};

export type PostSamplesResponse = PostSamplesResponses[keyof PostSamplesResponses];

export type GetPostsByPostIdCommentsData = {
    body?: never;
    path: {
        postId: string;
    };
    query?: {
        page?: number;
        size?: number;
    };
    url: '/posts/{postId}/comments';
};

export type GetPostsByPostIdCommentsResponses = {
    /**
     * OK
     */
    200: ApiResponsePageResponseCommentListItem;
};

export type GetPostsByPostIdCommentsResponse = GetPostsByPostIdCommentsResponses[keyof GetPostsByPostIdCommentsResponses];

export type PostPostsByPostIdCommentsData = {
    body: CommentCreateRequest;
    path: {
        postId: string;
    };
    query?: never;
    url: '/posts/{postId}/comments';
};

export type PostPostsByPostIdCommentsResponses = {
    /**
     * Created
     */
    201: ApiResponseCommentResponse;
};

export type PostPostsByPostIdCommentsResponse = PostPostsByPostIdCommentsResponses[keyof PostPostsByPostIdCommentsResponses];

export type PostBoardsData = {
    body: BoardCreateRequest;
    path?: never;
    query?: never;
    url: '/boards';
};

export type PostBoardsResponses = {
    /**
     * Created
     */
    201: ApiResponseBoardResponse;
};

export type PostBoardsResponse = PostBoardsResponses[keyof PostBoardsResponses];

export type GetBoardsByBoardIdPostsData = {
    body?: never;
    path: {
        boardId: string;
    };
    query?: {
        page?: number;
        size?: number;
    };
    url: '/boards/{boardId}/posts';
};

export type GetBoardsByBoardIdPostsResponses = {
    /**
     * OK
     */
    200: ApiResponsePageResponsePostListItem;
};

export type GetBoardsByBoardIdPostsResponse = GetBoardsByBoardIdPostsResponses[keyof GetBoardsByBoardIdPostsResponses];

export type PostBoardsByBoardIdPostsData = {
    body: PostCreateRequest;
    path: {
        boardId: string;
    };
    query?: never;
    url: '/boards/{boardId}/posts';
};

export type PostBoardsByBoardIdPostsResponses = {
    /**
     * Created
     */
    201: ApiResponsePostResponse;
};

export type PostBoardsByBoardIdPostsResponse = PostBoardsByBoardIdPostsResponses[keyof PostBoardsByBoardIdPostsResponses];

export type PostAuthSignupData = {
    body: SignupRequest;
    path?: never;
    query?: never;
    url: '/auth/signup';
};

export type PostAuthSignupResponses = {
    /**
     * Created
     */
    201: ApiResponseVoid;
};

export type PostAuthSignupResponse = PostAuthSignupResponses[keyof PostAuthSignupResponses];

export type PostAuthRefreshData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type PostAuthRefreshResponses = {
    /**
     * OK
     */
    200: ApiResponseTokenResponse;
};

export type PostAuthRefreshResponse = PostAuthRefreshResponses[keyof PostAuthRefreshResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostAuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginResponses = {
    /**
     * OK
     */
    200: ApiResponseTokenResponse;
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAdminUsersByIdPasswordResetData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/users/{id}/password-reset';
};

export type PostAdminUsersByIdPasswordResetResponses = {
    /**
     * OK
     */
    200: ApiResponsePasswordResetResponse;
};

export type PostAdminUsersByIdPasswordResetResponse = PostAdminUsersByIdPasswordResetResponses[keyof PostAdminUsersByIdPasswordResetResponses];

export type GetBoardsByBoardIdData = {
    body?: never;
    path: {
        boardId: string;
    };
    query?: never;
    url: '/boards/{boardId}';
};

export type GetBoardsByBoardIdResponses = {
    /**
     * OK
     */
    200: ApiResponseBoardResponse;
};

export type GetBoardsByBoardIdResponse = GetBoardsByBoardIdResponses[keyof GetBoardsByBoardIdResponses];

export type GetAdminUsersData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        size?: number;
    };
    url: '/admin/users';
};

export type GetAdminUsersResponses = {
    /**
     * OK
     */
    200: ApiResponsePageResponseAdminUserResponse;
};

export type GetAdminUsersResponse = GetAdminUsersResponses[keyof GetAdminUsersResponses];

export type DeleteAdminUsersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/users/{id}';
};

export type DeleteAdminUsersByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetAdminUsersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/users/{id}';
};

export type GetAdminUsersByIdResponses = {
    /**
     * OK
     */
    200: ApiResponseAdminUserResponse;
};

export type GetAdminUsersByIdResponse = GetAdminUsersByIdResponses[keyof GetAdminUsersByIdResponses];

export type DeleteSamplesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/samples/{id}';
};

export type DeleteSamplesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteCommentsByCommentIdData = {
    body?: never;
    path: {
        commentId: string;
    };
    query?: never;
    url: '/comments/{commentId}';
};

export type DeleteCommentsByCommentIdResponses = {
    /**
     * OK
     */
    200: unknown;
};
