// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { deleteAdminUsersById, deleteCommentsByCommentId, deleteCommentsByCommentIdReactions, deletePostsByPostId, deletePostsByPostIdReactions, deleteSamplesById, getAdminUsers, getAdminUsersById, getBoardsByBoardId, getBoardsByBoardIdPosts, getPostsByPostId, getPostsByPostIdComments, getSamples, type Options, postAdminUsersByIdPasswordReset, postAuthLogin, postAuthLogout, postAuthRefresh, postAuthSignup, postBoards, postBoardsByBoardIdPosts, postPostsByPostIdComments, postSamples, putCommentsByCommentIdReactions, putPostsByPostId, putPostsByPostIdReactions } from '../sdk.gen';
import type { DeleteAdminUsersByIdData, DeleteCommentsByCommentIdData, DeleteCommentsByCommentIdReactionsData, DeletePostsByPostIdData, DeletePostsByPostIdReactionsData, DeleteSamplesByIdData, GetAdminUsersByIdData, GetAdminUsersByIdResponse, GetAdminUsersData, GetAdminUsersResponse, GetBoardsByBoardIdData, GetBoardsByBoardIdPostsData, GetBoardsByBoardIdPostsResponse, GetBoardsByBoardIdResponse, GetPostsByPostIdCommentsData, GetPostsByPostIdCommentsResponse, GetPostsByPostIdData, GetPostsByPostIdResponse, GetSamplesData, GetSamplesResponse, PostAdminUsersByIdPasswordResetData, PostAdminUsersByIdPasswordResetResponse, PostAuthLoginData, PostAuthLoginResponse, PostAuthLogoutData, PostAuthRefreshData, PostAuthRefreshResponse, PostAuthSignupData, PostAuthSignupResponse, PostBoardsByBoardIdPostsData, PostBoardsByBoardIdPostsResponse, PostBoardsData, PostBoardsResponse, PostPostsByPostIdCommentsData, PostPostsByPostIdCommentsResponse, PostSamplesData, PostSamplesResponse, PutCommentsByCommentIdReactionsData, PutCommentsByCommentIdReactionsResponse, PutPostsByPostIdData, PutPostsByPostIdReactionsData, PutPostsByPostIdReactionsResponse, PutPostsByPostIdResponse } from '../types.gen';

export const deletePostsByPostIdMutation = (options?: Partial<Options<DeletePostsByPostIdData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeletePostsByPostIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeletePostsByPostIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deletePostsByPostId({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getPostsByPostIdQueryKey = (options: Options<GetPostsByPostIdData>) => createQueryKey('getPostsByPostId', options);

export const getPostsByPostIdOptions = (options: Options<GetPostsByPostIdData>) => queryOptions<GetPostsByPostIdResponse, AxiosError<DefaultError>, GetPostsByPostIdResponse, ReturnType<typeof getPostsByPostIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPostsByPostId({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPostsByPostIdQueryKey(options)
});

export const putPostsByPostIdMutation = (options?: Partial<Options<PutPostsByPostIdData>>): UseMutationOptions<PutPostsByPostIdResponse, AxiosError<DefaultError>, Options<PutPostsByPostIdData>> => {
    const mutationOptions: UseMutationOptions<PutPostsByPostIdResponse, AxiosError<DefaultError>, Options<PutPostsByPostIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putPostsByPostId({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deletePostsByPostIdReactionsMutation = (options?: Partial<Options<DeletePostsByPostIdReactionsData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeletePostsByPostIdReactionsData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeletePostsByPostIdReactionsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deletePostsByPostIdReactions({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const putPostsByPostIdReactionsMutation = (options?: Partial<Options<PutPostsByPostIdReactionsData>>): UseMutationOptions<PutPostsByPostIdReactionsResponse, AxiosError<DefaultError>, Options<PutPostsByPostIdReactionsData>> => {
    const mutationOptions: UseMutationOptions<PutPostsByPostIdReactionsResponse, AxiosError<DefaultError>, Options<PutPostsByPostIdReactionsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putPostsByPostIdReactions({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteCommentsByCommentIdReactionsMutation = (options?: Partial<Options<DeleteCommentsByCommentIdReactionsData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteCommentsByCommentIdReactionsData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteCommentsByCommentIdReactionsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteCommentsByCommentIdReactions({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const putCommentsByCommentIdReactionsMutation = (options?: Partial<Options<PutCommentsByCommentIdReactionsData>>): UseMutationOptions<PutCommentsByCommentIdReactionsResponse, AxiosError<DefaultError>, Options<PutCommentsByCommentIdReactionsData>> => {
    const mutationOptions: UseMutationOptions<PutCommentsByCommentIdReactionsResponse, AxiosError<DefaultError>, Options<PutCommentsByCommentIdReactionsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putCommentsByCommentIdReactions({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getSamplesQueryKey = (options?: Options<GetSamplesData>) => createQueryKey('getSamples', options);

export const getSamplesOptions = (options?: Options<GetSamplesData>) => queryOptions<GetSamplesResponse, AxiosError<DefaultError>, GetSamplesResponse, ReturnType<typeof getSamplesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSamples({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSamplesQueryKey(options)
});

export const postSamplesMutation = (options?: Partial<Options<PostSamplesData>>): UseMutationOptions<PostSamplesResponse, AxiosError<DefaultError>, Options<PostSamplesData>> => {
    const mutationOptions: UseMutationOptions<PostSamplesResponse, AxiosError<DefaultError>, Options<PostSamplesData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postSamples({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getPostsByPostIdCommentsQueryKey = (options: Options<GetPostsByPostIdCommentsData>) => createQueryKey('getPostsByPostIdComments', options);

export const getPostsByPostIdCommentsOptions = (options: Options<GetPostsByPostIdCommentsData>) => queryOptions<GetPostsByPostIdCommentsResponse, AxiosError<DefaultError>, GetPostsByPostIdCommentsResponse, ReturnType<typeof getPostsByPostIdCommentsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPostsByPostIdComments({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPostsByPostIdCommentsQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getPostsByPostIdCommentsInfiniteQueryKey = (options: Options<GetPostsByPostIdCommentsData>): QueryKey<Options<GetPostsByPostIdCommentsData>> => createQueryKey('getPostsByPostIdComments', options, true);

export const getPostsByPostIdCommentsInfiniteOptions = (options: Options<GetPostsByPostIdCommentsData>) => infiniteQueryOptions<GetPostsByPostIdCommentsResponse, AxiosError<DefaultError>, InfiniteData<GetPostsByPostIdCommentsResponse>, QueryKey<Options<GetPostsByPostIdCommentsData>>, number | Pick<QueryKey<Options<GetPostsByPostIdCommentsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetPostsByPostIdCommentsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getPostsByPostIdComments({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPostsByPostIdCommentsInfiniteQueryKey(options)
});

export const postPostsByPostIdCommentsMutation = (options?: Partial<Options<PostPostsByPostIdCommentsData>>): UseMutationOptions<PostPostsByPostIdCommentsResponse, AxiosError<DefaultError>, Options<PostPostsByPostIdCommentsData>> => {
    const mutationOptions: UseMutationOptions<PostPostsByPostIdCommentsResponse, AxiosError<DefaultError>, Options<PostPostsByPostIdCommentsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postPostsByPostIdComments({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postBoardsMutation = (options?: Partial<Options<PostBoardsData>>): UseMutationOptions<PostBoardsResponse, AxiosError<DefaultError>, Options<PostBoardsData>> => {
    const mutationOptions: UseMutationOptions<PostBoardsResponse, AxiosError<DefaultError>, Options<PostBoardsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postBoards({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getBoardsByBoardIdPostsQueryKey = (options: Options<GetBoardsByBoardIdPostsData>) => createQueryKey('getBoardsByBoardIdPosts', options);

export const getBoardsByBoardIdPostsOptions = (options: Options<GetBoardsByBoardIdPostsData>) => queryOptions<GetBoardsByBoardIdPostsResponse, AxiosError<DefaultError>, GetBoardsByBoardIdPostsResponse, ReturnType<typeof getBoardsByBoardIdPostsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getBoardsByBoardIdPosts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getBoardsByBoardIdPostsQueryKey(options)
});

export const getBoardsByBoardIdPostsInfiniteQueryKey = (options: Options<GetBoardsByBoardIdPostsData>): QueryKey<Options<GetBoardsByBoardIdPostsData>> => createQueryKey('getBoardsByBoardIdPosts', options, true);

export const getBoardsByBoardIdPostsInfiniteOptions = (options: Options<GetBoardsByBoardIdPostsData>) => infiniteQueryOptions<GetBoardsByBoardIdPostsResponse, AxiosError<DefaultError>, InfiniteData<GetBoardsByBoardIdPostsResponse>, QueryKey<Options<GetBoardsByBoardIdPostsData>>, number | Pick<QueryKey<Options<GetBoardsByBoardIdPostsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetBoardsByBoardIdPostsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getBoardsByBoardIdPosts({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getBoardsByBoardIdPostsInfiniteQueryKey(options)
});

export const postBoardsByBoardIdPostsMutation = (options?: Partial<Options<PostBoardsByBoardIdPostsData>>): UseMutationOptions<PostBoardsByBoardIdPostsResponse, AxiosError<DefaultError>, Options<PostBoardsByBoardIdPostsData>> => {
    const mutationOptions: UseMutationOptions<PostBoardsByBoardIdPostsResponse, AxiosError<DefaultError>, Options<PostBoardsByBoardIdPostsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postBoardsByBoardIdPosts({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postAuthSignupMutation = (options?: Partial<Options<PostAuthSignupData>>): UseMutationOptions<PostAuthSignupResponse, AxiosError<DefaultError>, Options<PostAuthSignupData>> => {
    const mutationOptions: UseMutationOptions<PostAuthSignupResponse, AxiosError<DefaultError>, Options<PostAuthSignupData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthSignup({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postAuthRefreshMutation = (options?: Partial<Options<PostAuthRefreshData>>): UseMutationOptions<PostAuthRefreshResponse, AxiosError<DefaultError>, Options<PostAuthRefreshData>> => {
    const mutationOptions: UseMutationOptions<PostAuthRefreshResponse, AxiosError<DefaultError>, Options<PostAuthRefreshData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthRefresh({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postAuthLogoutMutation = (options?: Partial<Options<PostAuthLogoutData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostAuthLogoutData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostAuthLogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthLogout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postAuthLoginMutation = (options?: Partial<Options<PostAuthLoginData>>): UseMutationOptions<PostAuthLoginResponse, AxiosError<DefaultError>, Options<PostAuthLoginData>> => {
    const mutationOptions: UseMutationOptions<PostAuthLoginResponse, AxiosError<DefaultError>, Options<PostAuthLoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthLogin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postAdminUsersByIdPasswordResetMutation = (options?: Partial<Options<PostAdminUsersByIdPasswordResetData>>): UseMutationOptions<PostAdminUsersByIdPasswordResetResponse, AxiosError<DefaultError>, Options<PostAdminUsersByIdPasswordResetData>> => {
    const mutationOptions: UseMutationOptions<PostAdminUsersByIdPasswordResetResponse, AxiosError<DefaultError>, Options<PostAdminUsersByIdPasswordResetData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAdminUsersByIdPasswordReset({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getBoardsByBoardIdQueryKey = (options: Options<GetBoardsByBoardIdData>) => createQueryKey('getBoardsByBoardId', options);

export const getBoardsByBoardIdOptions = (options: Options<GetBoardsByBoardIdData>) => queryOptions<GetBoardsByBoardIdResponse, AxiosError<DefaultError>, GetBoardsByBoardIdResponse, ReturnType<typeof getBoardsByBoardIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getBoardsByBoardId({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getBoardsByBoardIdQueryKey(options)
});

export const getAdminUsersQueryKey = (options?: Options<GetAdminUsersData>) => createQueryKey('getAdminUsers', options);

export const getAdminUsersOptions = (options?: Options<GetAdminUsersData>) => queryOptions<GetAdminUsersResponse, AxiosError<DefaultError>, GetAdminUsersResponse, ReturnType<typeof getAdminUsersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAdminUsers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAdminUsersQueryKey(options)
});

export const getAdminUsersInfiniteQueryKey = (options?: Options<GetAdminUsersData>): QueryKey<Options<GetAdminUsersData>> => createQueryKey('getAdminUsers', options, true);

export const getAdminUsersInfiniteOptions = (options?: Options<GetAdminUsersData>) => infiniteQueryOptions<GetAdminUsersResponse, AxiosError<DefaultError>, InfiniteData<GetAdminUsersResponse>, QueryKey<Options<GetAdminUsersData>>, number | Pick<QueryKey<Options<GetAdminUsersData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetAdminUsersData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getAdminUsers({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAdminUsersInfiniteQueryKey(options)
});

export const deleteAdminUsersByIdMutation = (options?: Partial<Options<DeleteAdminUsersByIdData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteAdminUsersByIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteAdminUsersByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteAdminUsersById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAdminUsersByIdQueryKey = (options: Options<GetAdminUsersByIdData>) => createQueryKey('getAdminUsersById', options);

export const getAdminUsersByIdOptions = (options: Options<GetAdminUsersByIdData>) => queryOptions<GetAdminUsersByIdResponse, AxiosError<DefaultError>, GetAdminUsersByIdResponse, ReturnType<typeof getAdminUsersByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAdminUsersById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAdminUsersByIdQueryKey(options)
});

export const deleteSamplesByIdMutation = (options?: Partial<Options<DeleteSamplesByIdData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteSamplesByIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteSamplesByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteSamplesById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteCommentsByCommentIdMutation = (options?: Partial<Options<DeleteCommentsByCommentIdData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteCommentsByCommentIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteCommentsByCommentIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteCommentsByCommentId({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
